version: "3.9"
services:
  nsa-db:
    image: postgres
    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
      - nsa-db:/var/lib/postgresql/data
    networks:
      - nsa-net
  nsa:
    restart: always
    depends_on:
      - nsa-db
    build:
      context: .
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      PG_HOST: nsa-db
      PG_PASSWORD: "${PG_PASSWORD}"
    networks:
      - nsa-net
networks:
  nsa-net:
    driver: bridge
volumes:
  nsa-db: