name: build release and push to docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Scaleway
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_DEFAULT_ZONE: fr-par-1
        run: |
          docker run --rm -e SCW_ACCESS_KEY -e SCW_SECRET_KEY -e SCW_DEFAULT_ORGANIZATION_ID -e SCW_DEFAULT_ZONE scaleway/cli:latest registry login
      - name: Derive version from Cargo.toml
        run: |
          VERSION=$(sed -n "s/^version = \"\(\S*\)\"$/\1/p" Cargo.toml)
          echo "::set-env name=VERSION::$VERSION"
      - name: Build, tag, and push
        uses: docker/build-push-action@v3.1.1
        with:
          build-args: profile=release
          push: true
          tags: "${{ secrets.REGISTRY }}/nsa:${{ env.VERSION }}"