name: build release and push to docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Scaleway
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_DEFAULT_ZONE: fr-par-1
        run: |
          curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.5.4/scaleway-cli_2.5.4_linux_amd64"
          chmod +x /usr/local/bin/scw
          scw registry login
      - name: Derive version from Cargo.toml
        run: |
          VERSION=$(sed -n "s/^version = \"\(\S*\)\"$/\1/p" Cargo.toml)
          echo "::set-env name=VERSION::$VERSION"
      - name: Build, tag, and push
        uses: docker/build-push-action@v3.1.1
        with:
          build-args: profile=release
          push: true
          tags: "${{ secrets.REGISTRY }}/nsa:${{ env.VERSION }}"